version: '3'
services:
  app:
    #app_goの中にあるDockerfileの読み込み
    build: .
    container_name: "alligator"
    # containerの起動状態を維持
    tty: true
    # ホストのport8080をコンテナのport8080にポートフォワード
    ports: 
      - "8080:8080"
    #ホストのディレクトリをコンテナにマウント
    volumes:
      - .:/go